version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    networks:
      - my_network

networks:
  my_network:
    external: true
